# Use root/example as user/password credentials

x-common-variables: &common-variables
  REACT_APP_SERVER_PORT: 8000

services:

  db:
    image: mysql:9.2
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: mysqladmin ping -h localhost
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    depends_on:
      - db
    image: adminer
    ports:
      - 8080:8080
    environment:
      <<: *common-variables

  server:
    restart: on-failure
    image: python-api-2
    build:
      context: ./server
      dockerfile: DockerfilePython
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/public-users"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command: uvicorn server:app --proxy-headers --host 0.0.0.0 --port 8000

  react:
    image: react
    build:
      context: .
      dockerfile: DockerfileReact
    ports:
      - 3000:3000
    environment:
      - VITE_REACT_APP_SERVER_URL=http://localhost:8000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server
    depends_on:
      server:
        condition: service_healthy
    command: npm run dev -- --host 0.0.0.0 --port 3000
    tty: true
