services:
  react:
    image: react
    build:
      context: .
      dockerfile: ./DockerfileReact
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_URL
    volumes:
      - .:/app
      - /app/node_modules
      - /app/server
    command: npm start

