# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:9.2
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./sqlfiles/:/docker-entrypoint-initdb.d/
  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080

