name: CI/CD – React, FastAPI, Docker, Cypress

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies and run unit/integration tests
        env:
          VITE_REACT_APP_SERVER_URL: ${{ secrets.VITE_REACT_APP_SERVER_URL }}
        run: |
          npm ci
          npm run coverage
          npm run jsdoc
          npm run build

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload dist for GitHub Pages
        uses: actions/upload-artifact@v4
        with:
          name: github-pages-dist
          path: dist

  docker_and_e2e:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - uses: actions/checkout@v4

      - name: Recreate .env file securely
        run: echo "$ENV_FILE" > .env
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}

      - name: Start Docker environment (v4)
        run: docker compose -f docker-compose-v4.yml up -d --build
        working-directory: ./

      - name: Afficher les logs des services
        run: |
          echo "=== Logs de la base de données ==="
          docker logs db || true
          echo "=== Logs du serveur ==="
          docker logs server || true
          echo "=== Logs de React ==="
          docker logs integ-deploiement-react-1 || true
        working-directory: ./

      - name: Wait for services to be ready
        run: |
          echo "Waiting for backend (http://localhost:8000) to be ready..."
          timeout 120 bash -c 'until curl -f http://localhost:8000/public-users > /dev/null 2>&1; do echo "Backend not ready yet..."; sleep 5; done'
          echo "Backend is ready!"
          echo "Waiting for frontend (http://localhost:3000) to be ready..."
          timeout 120 bash -c 'until curl -f http://localhost:3000 > /dev/null 2>&1; do echo "Frontend not ready yet..."; sleep 5; done'
          echo "Frontend is ready!"
        working-directory: ./

      - name: Afficher les logs du backend
        run: docker logs server || true
        working-directory: ./

      - name: Lister les conteneurs Docker
        run: docker ps -a
        working-directory: ./

      - name: Afficher les logs du front
        run: docker logs integ-deploiement-react-1
        working-directory: ./

      - name: Vérifier que le front répond
        run: curl -v http://localhost:3000
        working-directory: ./

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Clean node_modules
        run: rm -rf node_modules
        working-directory: ./

      - name: Fix permissions
        run: |
          sudo chown -R $USER:$USER .
        working-directory: ./

      - name: Install front dependencies
        run: npm ci
        working-directory: ./

      - name: Afficher le HTML retourné par le front
        run: curl -s http://localhost:3000/integ-deploiement/ > page.html && head -40 page.html
        working-directory: ./

      - name: Derniers logs du front
        run: docker logs integ-deploiement-react-1 | tail -40
        working-directory: ./

      - name: Run Cypress tests against Docker environment
        env:
          VITE_REACT_APP_SERVER_URL: http://localhost:8000
          CYPRESS_BASE_URL: http://localhost:3000/integ-deploiement/
        run: |
          npx cypress install
          npx cypress run --config-file cypress.config.cjs --browser chrome --headless
        working-directory: ./

  deploy_pages:
    needs: build_test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Download dist from previous job
        uses: actions/download-artifact@v4
        with:
          name: github-pages-dist
          path: dist

      - name: Install dependencies
        run: npm ci

      - name: Build for GitHub Pages
        run: npm run build
        env:
          VITE_BASE_PATH: /integ-deploiement/
          VITE_REACT_APP_SERVER_URL: ${{ secrets.VITE_REACT_APP_SERVER_URL }}

      - name: Create .nojekyll
        run: echo > dist/.nojekyll
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

  deploy_npm:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Babel dependencies
        run: npm install --save-dev @babel/core @babel/cli @babel/preset-env @babel/preset-react

      - name: Build npm package
        run: npm run build-npm-ci
        working-directory: ./

      - name: Configure Git
        run: |
          git config --global user.email "andreas.castello06@gmail.com"
          git config --global user.name "andreascastello"
      - name: Setup npm auth
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Check if version is already published
        run: |
          PKG_NAME=$(node -p "require('./package.json').name")
          PKG_VERSION=$(node -p "require('./package.json').version")
          if npm view "$PKG_NAME@$PKG_VERSION" > /dev/null 2>&1; then
            echo "Version $PKG_VERSION already exists on NPM. Skipping publish."
            exit 1
          fi
      - name: Publish to NPM
        run: npm publish
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy_backend_vercel:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy FastAPI to Vercel
        run: npx vercel deploy --prod --yes --token ${{ secrets.INTEG_TOKEN }}
        working-directory: ./server

  build-and-push-react:
    needs: build_test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: andreascastello06
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/andreascastello06/ci_cd_react_ynov
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: DockerfileReact
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  build-and-push-fastapi:
    needs: build_test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: andreascastello06
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: docker.io/andreascastello06/ci_cd_fastapi_ynov
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/DockerfilePython
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  dispatch_to_express_mongodb_app:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Fire event to express-mongodb-app
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_DISPATCH }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/andreascastello/express-mongodb-app/dispatches \
            -d '{"event_type": "trigger-ci"}'

  dispatch_to_terraform_archi:
    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - name: Fire event to terraform-archi
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_DISPATCH }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/andreascastello/terraform-archi/dispatches \
            -d '{"event_type": "trigger-ci"}'