name: CI and Dispatch

on:
  push:
    branches:
      - main

jobs:
  build-and-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Exemple d'étapes build/test pour ce repo
      # - name: Install dependencies
      #   run: ...
      # - name: Run tests
      #   run: ...

      - name: Dispatch to express-mongodb-app
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_DISPATCH }}
          repository: andreascastello/express-mongodb-app
          event-type: trigger-ci

      - name: Dispatch to terraform-archi
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_DISPATCH }}
          repository: andreascastello/terraform-archi
          event-type: trigger-ci 