name: CI on Dispatch

on:
  repository_dispatch:
    types: [trigger-ci]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Exemple d'étapes build/test pour ce repo
      # - name: Install dependencies
      #   run: ...
      # - name: Run tests
      #   run: ... 